package com.example.influencify.ui.screens.categories

val CategoriesList = listOf(
    "Cars and motor vehicles",
    "Business and startups",
    "Video games",
    "Pets and animals",
    "Kids and parenting",
    "Food and cooking",
    "Health and medicine",
    "Celebrities and lifestyle",
    "Investments",
    "Foreign languages",
    "Computer science / Internet technologies",
    "Art and design",
    "History",
    "Movies",
    "Books, audiobooks, and podcasts",
    "Beauty and personal care",
    "Cryptocurrencies",
    "Culture and events",
    "Curious facts",
    "Marketing and PR",
    "Fashion and style",
    "Motivation and self-development",
    "Music",
    "Science and technology",
    "Real estate",
    "News and media",
    "Education",
    "Recreation and entertainment",
    "Psychology and relationships",
    "Travel and tourism",
    "Jobs and vacancies",
    "Religion and spirituality",
    "Sales and discounts",
    "Sports",
    "Home and architecture",
    "Trading",
    "Sustainable lifestyle",
    "Finance and economics",
    "Hobbies and activities",
    "Esotericism, astrology, mysticism",
    "Economy and finance"
)